In [17]:
import csv


with open("C:/Users/lenovo/OneDrive/Desktop/Travel details dataset.csv","r") as file_object:

    data_table = csv.reader(file_object) 
    
    for line in data_table:
        if line[7]== "Female" and line[1]== "Paris" and line[2] and line[3]:

            print(line[5])

Sarah Johnson
Lily Nguyen
Rachel Sanders
Olivia Green

In [3]:
import csv


with open("C:/Users/lenovo/OneDrive/Desktop/covid.csv","r") as file_object:

    data_table = csv.reader(file_object) 
    
    for line in data_table:   
        if line[1]== "India":
            print(line)

['2', 'India', '44,924,811', '', '531,424', '', '44,335,977', '57,410', 'N/A', '31,938', '378', '925,077,322', '657,654', '1,406,631,776', 'Asia', '31', '2,647', '2', '', '', '41']

In [17]:
import csv
i=0
with open("C:/Users/lenovo/OneDrive/Desktop/Travel details dataset.csv","r") as file_object:
    data_table= csv.reader(file_object)
    
    for line in data_table:
        print(line[1])

Destination
London, UK
Phuket, Thailand
Bali, Indonesia
New York, USA
Tokyo, Japan
Paris, France
Sydney, Australia
Rio de Janeiro, Brazil
Amsterdam, Netherlands
Dubai, United Arab Emirates
Cancun, Mexico
Barcelona, Spain
Honolulu, Hawaii
Berlin, Germany
Marrakech, Morocco
Edinburgh, Scotland
Paris
Bali
London
Tokyo
New York
Sydney
Rome
Bangkok
Paris
Hawaii
Barcelona
Japan
Thailand
France
Australia
Brazil
Greece
Egypt
Mexico
Italy
Spain
Canada
Paris, France
Sydney, Australia
Tokyo, Japan
Cancun, Mexico
Rio de Janeiro, Brazil
London, UK
Barcelona, Spain
New York City, USA
Bangkok, Thailand
Vancouver, Canada
Amsterdam, Netherlands
Paris, France
Tokyo, Japan
Sydney, AUS
New York, USA
Rio de Janeiro, Brazil
Bangkok, Thailand
London, UK
Barcelona, Spain
Seoul, South Korea
Los Angeles, USA
Rome, Italy
Paris
Tokyo
Cape Town
Sydney
Barcelona
Bali
Paris
New York
Bangkok
Rome
Bali

Bali, Indonesia
Tokyo, Japan
Cancun, Mexico
Paris, France
Cape Town, SA
Bali, Indonesia
Sydney, Aus
Bangkok, Thai
New York, USA
Phuket, Thai
Rome, Italy
Paris
Tokyo
Bali
Sydney
New York
London
Dubai
Bangkok
Rome
Bali
Seoul
Paris
Tokyo
Sydney
London
New York
Rome
Bangkok
Cape Town
Rio de Janeiro
Bali
Amsterdam
Paris
Tokyo
New York
Bali
Sydney
London
Phuket
Rome
Santorini
Dubai
Phnom Penh
Tokyo, Japan
Paris, France
Sydney, Aus
Rome, Italy
Bali, Indonesia
Cancun, Mexico
Athens, Greece
Tokyo, Japan
Sydney, Aus
Paris, France
Bali, Indonesia

Paris, France
Tokyo, Japan
Cape Town, South Africa
Sydney, Australia
Rome, Italy
New York City, USA
Rio de Janeiro, Brazil
Vancouver, Canada
Bangkok, Thailand
Barcelona, Spain
Auckland, New Zealand

In [10]:
import csv

field =['Name','Branch','Year','CGPA']
rows=[['Akash','CS','Final Year',8.0],
      ['Ankitha','CS','Final Year',8.5],
      ['Chandru','CS','Final Year',7.0],
      ['Arvind','CS','Final Year',9.0],
      ['Ravi','CS','Final Year',8.0],
      ['Boomik','CS','Final Year',8.5],
      ['Umar','CS','Final Year',7.0],
      ['Nikhil','Mech','Final Year',8.5],
      ['Sangmesh','Mech','Final Year',8.5],
      ['Ragu','CS','Final Year',9.0]
]

filename='keonics.csv'

with open(filename,'w') as csvfile:
    writer_object= csv.writer(csvfile)
    writer_object.writerow(field)
    writer_object.writerows(rows)


with open(filename,'r') as csvfile:
      data=csv.reader(csvfile)
      for line in data:
            print(line)

['Name', 'Branch', 'Year', 'CGPA']
[]
['Akash', 'CS', 'Final Year', '8.0']
[]
['Ankitha', 'CS', 'Final Year', '8.5']
[]
['Chandru', 'CS', 'Final Year', '7.0']
[]
['Arvind', 'CS', 'Final Year', '9.0']
[]
['Ravi', 'CS', 'Final Year', '8.0']
[]
['Boomik', 'CS', 'Final Year', '8.5']
[]
['Umar', 'CS', 'Final Year', '7.0']
[]
['Nikhil', 'Mech', 'Final Year', '8.5']
[]
['Sangmesh', 'Mech', 'Final Year', '8.5']
[]
['Ragu', 'CS', 'Final Year', '9.0']
[]

In [10]:
import csv


with open("C:/Users/lenovo/OneDrive/Desktop/sp500_index.csv","r") as file_object:

    data_table = csv.reader(file_object) 
    
    for line in data_table:   
        
        
        print(line[5])

Close
2823.81005859375
2713.830078125
2640.8701171875
2648.050048828125
2705.27001953125
2718.3701171875
2816.2900390625
2901.52001953125
2913.97998046875
2711.739990234375
2760.169921875
2506.85009765625
2704.10009765625
2784.489990234375
2834.39990234375
2945.830078125
2752.06005859375
2941.760009765625
2980.3798828125
2926.4599609375
2976.739990234375
3037.56005859375
3140.97998046875
3230.780029296875
3225.52001953125
2954.219970703125
2584.590087890625
2912.429931640625
3044.31005859375
3100.2900390625
3271.1201171875
3500.31005859375
3363.0
3269.9599609375
3621.6298828125
3756.070068359375
3714.239990234375
3811.14990234375
3972.889892578125
4181.169921875
4204.10986328125
4297.5
4395.259765625
4522.68017578125
4307.5400390625
4605.3798828125
4567.0
4766.18017578125
4515.5498046875
4373.93994140625
4530.41015625
4131.93017578125
4132.14990234375
3785.3798828125
4130.2900390625
3955.0
3585.6201171875
3871.97998046875
4080.110107421875
3839.5
4076.60009765625
3970.14990234375
4109.31005859375

In [ ]:
class bulb:
    ON = False
    OFF = True

    def status(attr1,attr2):
        print("ON:",attr1)
        print("OFF:",attr2)
    def switchON():